name: fs050w_signal_display
description: "FS050W 5G/4G Signal Display and Engineering App"
publish_to: "none"
version: 1.3.0+17

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3
  fl_chart: ^0.68.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_foreground_task: ^11.0.1
  flutter_local_notifications: ^17.1.2
  wakelock_plus: ^1.2.8
  network_info_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
